<br><br><br>
<form action="login.php" method="POST">
	<table align="center" cellspacing="0" cellpadding="0">
		<tr height="1px" bgcolor="orange"><td colspan="7"></td></tr>
		<tr height="5px"><td bgcolor="orange"></td><td colspan="5"></td><td bgcolor="orange"></td></tr>
		<tr height="25px">
			<td width="1px" bgcolor="orange"></td>
			<td width="5px"></td>
			<td colspan="3" bgcolor="orange" align="center"><b><font color="white">Đăng nhập</font></b></td>
			<td width="5px"></td>
			<td width="1px" bgcolor="orange"></td>
		</tr>
		<tr height="5px"><td bgcolor="orange"></td><td colspan="5"></td><td bgcolor="orange"></td></tr>
		<tr>
			<td bgcolor="orange"></td>
			<td></td>
			<td>Email</td>
			<td width="5px"></td>
			<td><input type="text" name="email" placeholder="Vui lòng nhập email"></td>
			<td></td>
			<td bgcolor="orange"></td>
		</tr>
		<tr height="2px"><td bgcolor="orange"></td><td colspan="5"></td><td bgcolor="orange"></td></tr>
		<tr>
			<td bgcolor="orange"></td>
			<td></td>
			<td>Mật khẩu</td>
			<td></td>
			<td><input type="password" name="password" placeholder="Vui lòng nhập mật khẩu"></td>
			<td></td>
			<td bgcolor="orange"></td>
		</tr>
		<tr height="5px"><td bgcolor="orange"></td><td colspan="5"></td><td bgcolor="orange"></td></tr>
		<tr>
			<td bgcolor="orange"></td>
			<td colspan="5" align="center"><input type="submit" value="Đăng nhập"></td>
			<td bgcolor="orange"></td>
		</tr>
		<tr height="5px"><td bgcolor="orange"></td><td colspan="5"></td><td bgcolor="orange"></td></tr>
		<tr height="1px" bgcolor="orange"><td colspan="7"></td></tr>
	</table>
</form>